<!--
SPDX-FileCopyrightText: 2026 Neptuwunium

SPDX-License-Identifier: EUPL-1.2
-->

<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<TargetFramework>net11.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Serilog" Version="4.3.1"/>
		<PackageReference Include="System.IO.Hashing" Version="11.0.0-preview.4.26230.115"/>
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\Neptune\Charon\Charon.csproj"/>
		<ProjectReference Include="..\Neptune\Triton\Triton.csproj"/>
		<ProjectReference Include="..\Neptune\Pluto\Pluto.csproj"/>
		<ProjectReference Include="..\Neptune\Pluto.SourceGen\Pluto.SourceGen.csproj" OutputItemType="Analyzer" ReferenceOutputAssembly="false"/>
	</ItemGroup>

</Project>
